# Write a Python program to find the indices of sorted elements of this list [10,5,8,,3,2,1]

In [6]:
import numpy as np
array = np.array([10,5,8,3,2,1])
print(array)
indices = np.argsort(array)
print(indices)
order = np.sort(array)
print(order)

[10  5  8  3  2  1]
[5 4 3 1 2 0]
[ 1  2  3  5  8 10]


# Write a Python program to split a string of words separated by spaces into two lists

In [52]:

def test(string):
    import re
    spl = re.split(r"([ ,]+)", string)
    return [spl[::2], spl[1::2]]

str = 'Python is a high-level, general-purpose programming language Its design philosophy emphasizes code readability with the use of significant indentation'

print(test(str))



[['Python', 'is', 'a', 'high-level', 'general-purpose', 'programming', 'language', 'Its', 'design', 'philosophy', 'emphasizes', 'code', 'readability', 'with', 'the', 'use', 'of', 'significant', 'indentation'], [' ', ' ', ' ', ', ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']]


# Write a Python program to generate a random n numbers from a given list.

In [1]:
import random 
lis = [10,5,8,3,2,1]
randInrang = random.randint(0,len(lis))
print('the random',randInrang,'number form the list is :',random.choices(lis,k=randInrang))

the random 4 number form the list is : [2, 2, 3, 1]
